I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prologue.rpy", line 138, in script
    $ set_mode_adv()
  File "game/prologue.rpy", line 138, in <module>
    $ set_mode_adv()
NameError: name 'set_mode_adv' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prologue.rpy", line 138, in script
    $ set_mode_adv()
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/prologue.rpy", line 138, in <module>
    $ set_mode_adv()
NameError: name 'set_mode_adv' is not defined

Windows-10-10.0.18362
Ren'Py 7.4.3.1414
Cloud Inc. Alpha 0.1.2
Sat Mar 27 12:26:28 2021
